  version: '3'
  services:
    gym-mysql:
      image: mysql:5.7.16
      environment:
        MYSQL_ROOT_PASSWORD: Admin.2020
        MYSQL_DATABASE: app_fisic
        MYSQL_USER: usr_node
        MYSQL_PASSWORD: N0D3GYM2020
      ports:
        - 33069:3306
      volumes:
        - ./database/schemas:/var/lib/mysql
      networks: 
        node_net:
          ipv4_address: 172.16.100.9
    gym-node:
      container_name: exampleapp
      restart: always
      build: .
      ports:
        - "5000:3000"
      links: 
          - gym-mysql
      volumes: 
          - .:/usr/src/app
      networks: 
        node_net:
          ipv4_address: 172.16.100.10
  networks:
    node_net:
      driver: bridge
      ipam:
        driver: default
        config:
          -
            subnet: 172.16.100.0/24
      

