export enum GroupQualify{
    TIEMPO_EJECUCION    = 'TIEMPO_EJECUCION',
    NUMERO_REPETICIONES = 'NUMERO_REPETICIONES',
    COGNITIVO           = 'APTITUD_COGNITIVA',
    APTITUD_FISICA      = 'APTITUD_FISICA'
}